### PR TITLE
Created Scoring Pipeline Deployment Intro Tutorial

### PR DESCRIPTION
**Pull request by james94**
Tested on Driverless AI Aquarium Lab 9. Driverless AI version 1.8.7.1

Outline of the tutorial includes
- Tour of Prebuilt Experiment
- Concepts
- Batch Scoring
- Interactive Scoring (REST Server and AWS Lambda)
- Challenge
- Next Steps
- Build Driverless AI Experiment in which user imports preprocessed hydraulic
data using Data Recipe URL
- Point to H2O.ai Community AI Glossary

### CODE REVIEW

**Comment by james94** [comment]
@FrankJVA @Castro38 @5675sp 
Those links I got that are at the end of the prerequisites section I copied over from the **tutorial-template.md** file on the h2oai/tutorials repo, so the links are broken there too and don't point to the tutorials in the learning center.

https://github.com/h2oai/tutorials/blob/612d77bece6154cd99fc4f037f71e726f49af82e/Tutorial%20Template/tutorial-template/tutorial-template.md

I just wanted to share a heads up, so users who are building new tutorials don't run into this issue again if they start their tutorial based on the tutorial-template.md that is on the h2oai/tutorials repo.

**Comment by james94** [comment]
@FrankJVA 
I added the updates based on your feedback. Now there aren't broken links in the prerequisites section. I also updated the links that pointed to tutorials to point to h2o training tutorials.
I updated and tested the task 4 link to make sure it works. I verified it works on github web.

**Comment by james94** [comment]
@5675sp @Castro38 I updated the tutorial based on your feedback. Thanks.

**Comment by james94** [comment]
@Castro38 @5675sp @FrankJVA I incorporated EricGudgion's feedback. The tutorial should be ready to go now.

**Comment by Castro38** [comment]
> @FrankJVA @Castro38 @5675sp
> Those links I got that are at the end of the prerequisites section I copied over from the **tutorial-template.md** file on the h2oai/tutorials repo, so the links are broken there too and don't point to the tutorials in the learning center.
> 
> https://github.com/h2oai/tutorials/blob/612d77bece6154cd99fc4f037f71e726f49af82e/Tutorial%20Template/tutorial-template/tutorial-template.md
> 
> I just wanted to share a heads up, so users who are building new tutorials don't run into this issue again if they start their tutorial based on the tutorial-template.md that is on the h2oai/tutorials repo.

Hi James, we have two versions of the tutorials, on the master branch for github users and the gh-pages for the LMS. I had only updated the tutorials links for the LMS. The goal was to make those updates for this release. Thank you for updating the links :)

**Comment by james94** [comment]
@Castro38 removed the other installations in the prerequisites section

**Pull request merged**
